name: Deploy to PyPI

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest

  # deploy-test-pypi:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'
  #   - name: Install dependencies
  #     run: pip install setuptools wheel twine
  #   - name: Build package
  #     run: python setup.py sdist bdist_wheel
  #   - name: Publish to Test PyPI
  #     run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  #     env:
  #       TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  #       TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}

  # deploy-pypi:
  #   needs: deploy-test-pypi
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'
  #   - name: Install dependencies
  #     run: pip install setuptools wheel twine
  #   - name: Build package
  #     run: python setup.py sdist bdist_wheel
  #   - name: Publish to PyPI
  #     run: twine upload dist/*
  #     env:
  #       TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  #       TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
